version: '3'

services:

  frontend-admin:
    container_name: igetup_builder
    image: node:9.8
    command:
      - bash
      - -c
      - |
        cd /app
        npm link gulp
        gulp
        chmod -R 777 /app/dist
    tty: true
    volumes:
      - "./:/app"